using EVSRS.BusinessObjects.Base;
using System;

namespace EVSRS.BusinessObjects.Entity
{
    /// <summary>
    /// Represents a demand forecast for a specific time slot
    /// Generated by ForecastingService using historical data
    /// </summary>
    public class DemandForecast : BaseEntity
    {
        public string DepotId { get; set; } = string.Empty;
        
        /// <summary>
        /// NULL means forecast applies to all vehicle types at this depot
        /// </summary>
        public string? ModelId { get; set; }
        
        /// <summary>
        /// The future time slot this forecast is for
        /// </summary>
        public DateTime ForecastTime { get; set; }
        
        /// <summary>
        /// Predicted number of rental requests (demand)
        /// </summary>
        public decimal PredictedDemand { get; set; }
        
        /// <summary>
        /// Confidence score between 0 and 1
        /// </summary>
        public decimal? ConfidenceScore { get; set; }
        
        /// <summary>
        /// Forecasting method used: 'MA', 'P90', 'LSTM', 'Prophet', etc.
        /// </summary>
        public string? Method { get; set; }
        
        /// <summary>
        /// Timestamp when this forecast was generated
        /// </summary>
        public DateTime GeneratedAt { get; set; }
        
        /// <summary>
        /// Time horizon in minutes (typically 30)
        /// </summary>
        public int HorizonMinutes { get; set; } = 30;
        
        // Navigation properties
        public virtual Depot? Depot { get; set; }
        public virtual Model? Model { get; set; }
    }
}
