using EVSRS.BusinessObjects.Base;
using System;

namespace EVSRS.BusinessObjects.Entity
{
    /// <summary>
    /// Represents a capacity rebalancing plan (relocate/purchase vehicles)
    /// Generated by CapacityPlanner based on demand forecasts
    /// </summary>
    public class RebalancingPlan : BaseEntity
    {
        /// <summary>
        /// Target date for this rebalancing action
        /// </summary>
        public DateTime PlanDate { get; set; }
        
        /// <summary>
        /// Source depot (NULL if ActionType = PURCHASE)
        /// </summary>
        public string? FromDepotId { get; set; }
        
        /// <summary>
        /// Destination depot
        /// </summary>
        public string ToDepotId { get; set; } = string.Empty;
        
        /// <summary>
        /// Vehicle model/type to relocate or purchase
        /// </summary>
        public string ModelId { get; set; } = string.Empty;
        
        /// <summary>
        /// Number of vehicles to relocate/purchase
        /// </summary>
        public int Quantity { get; set; }
        
        /// <summary>
        /// Action type: RELOCATE, PURCHASE, MAINTENANCE
        /// </summary>
        public string ActionType { get; set; } = "RELOCATE";
        
        /// <summary>
        /// Priority (0=low, 100=urgent)
        /// </summary>
        public int Priority { get; set; }
        
        /// <summary>
        /// Estimated cost of this action
        /// </summary>
        public decimal? EstimatedCost { get; set; }
        
        /// <summary>
        /// Status: PROPOSED, APPROVED, EXECUTED, CANCELLED
        /// </summary>
        public string Status { get; set; } = "PROPOSED";
        
        /// <summary>
        /// Explanation why this plan was generated
        /// </summary>
        public string? Reason { get; set; }
        
        /// <summary>
        /// When this plan was approved
        /// </summary>
        public DateTime? ApprovedAt { get; set; }
        
        /// <summary>
        /// Who approved this plan (UserId)
        /// </summary>
        public string? ApprovedBy { get; set; }
        
        // Navigation properties
        public virtual Depot? FromDepot { get; set; }
        public virtual Depot? ToDepot { get; set; }
        public virtual Model? Model { get; set; }
    }
}
